/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7993c19f225c8ecf60299c1fbfd39eb8)
interface __BaseEnv_Env {
	DB: D1Database;
	AI: Ai;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
