/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9b25b80a412797c1ace2dd8088d6e84f)
interface __BaseEnv_Env {
	DATABASE: D1Database;
	AI: Ai;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	DATA_SERVICE: Fetcher /* data-service */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
