/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ad2f9450d18a1f2f49668c5558cf1c4c)
interface __BaseEnv_Env {
	R2_BUCKET: R2Bucket;
	DATABASE: D1Database;
	AI: Ai;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	DATA_SERVICE: Fetcher /* data-service */;
	USER_ONBOARDING_WORKFLOW: Workflow /* UserOnboardingWorkflow */;
	ORG_ONBOARDING_WORKFLOW: Workflow /* OrgOnboardingWorkflow */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
