packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
  sharp: true
  workerd: true
  '@google/genai': true
  '@sentry/cli': true
  better-sqlite3: true
  protobufjs: true
onlyBuiltDependencies:
  - esbuild
  - lightningcss
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
