import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*.{js,ts,tsx,vue}": "vp check --fix",
  },
  lint: {
    jsPlugins: [
      { name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
      { name: "@stylistic", specifier: "@stylistic/eslint-plugin" },
    ],
    plugins: ["typescript", "import", "react", "jsx-a11y", "vitest"],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
    env: { builtin: true },
    categories: {
      correctness: "off",
    },
    ignorePatterns: [
      "**/.nx/**",
      "**/.svelte-kit/**",
      "**/build/**",
      "**/coverage/**",
      "**/dist/**",
      "**/snap/**",
      "**/vite.config.*.timestamp-*.*",
      "eslint.config.js",
      ".prettierrc",
      "routeTree.gen.ts",
    ],
    overrides: [
      {
        files: ["apps/web/**/*.{js,ts,tsx}"],
        plugins: ["typescript", "import"],
        env: {
          es2020: true,
          browser: true,
        },
        rules: {
          "for-direction": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-else-if": "error",
          "no-duplicate-case": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-global-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-shadow": "warn",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-var": "error",
          "no-with": "error",
          "prefer-const": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
          "import/first": "error",
          "import/newline-after-import": "error",
          "import/no-commonjs": "error",
          "import/no-duplicates": "error",
          "@stylistic/spaced-comment": "error",
          "typescript/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": false,
              "ts-ignore": "allow-with-description",
            },
          ],
          "typescript/consistent-type-imports": [
            "error",
            {
              prefer: "type-imports",
            },
          ],
          "typescript/method-signature-style": ["error", "property"],
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-for-in-array": "error",
          "typescript/no-inferrable-types": [
            "error",
            {
              ignoreParameters: true,
            },
          ],
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-unnecessary-type-assertion": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-for-of": "warn",
          "typescript/triple-slash-reference": "error",
        },
      },
      {
        files: ["apps/web/**/*.vue"],
        plugins: ["typescript", "import"],
        env: {
          browser: true,
        },
        rules: {
          "for-direction": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-else-if": "error",
          "no-duplicate-case": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-global-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-shadow": "warn",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-var": "error",
          "no-with": "error",
          "prefer-const": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
          "import/first": "error",
          "import/newline-after-import": "error",
          "import/no-commonjs": "error",
          "import/no-duplicates": "error",
          "@stylistic/spaced-comment": "error",
          "typescript/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": false,
              "ts-ignore": "allow-with-description",
            },
          ],
          "typescript/consistent-type-imports": [
            "error",
            {
              prefer: "type-imports",
            },
          ],
          "typescript/method-signature-style": ["error", "property"],
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-for-in-array": "error",
          "typescript/no-inferrable-types": [
            "error",
            {
              ignoreParameters: true,
            },
          ],
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-unnecessary-type-assertion": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-for-of": "warn",
          "typescript/triple-slash-reference": "error",
        },
      },
      {
        files: ["packages/ui/**/*.{js,ts,tsx}"],
        plugins: ["typescript", "import"],
        env: {
          es2020: true,
          browser: true,
        },
        rules: {
          "for-direction": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-else-if": "error",
          "no-duplicate-case": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-global-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-shadow": "warn",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-var": "error",
          "no-with": "error",
          "prefer-const": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
          "import/first": "error",
          "import/newline-after-import": "error",
          "import/no-commonjs": "error",
          "import/no-duplicates": "error",
          "@stylistic/spaced-comment": "error",
          "typescript/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": false,
              "ts-ignore": "allow-with-description",
            },
          ],
          "typescript/consistent-type-imports": [
            "error",
            {
              prefer: "type-imports",
            },
          ],
          "typescript/method-signature-style": ["error", "property"],
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-for-in-array": "error",
          "typescript/no-inferrable-types": [
            "error",
            {
              ignoreParameters: true,
            },
          ],
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-unnecessary-type-assertion": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-for-of": "warn",
          "typescript/triple-slash-reference": "error",
        },
      },
      {
        files: ["packages/ui/**/*.vue"],
        plugins: ["typescript", "import"],
        env: {
          browser: true,
        },
        rules: {
          "for-direction": "error",
          "no-async-promise-executor": "error",
          "no-case-declarations": "error",
          "no-class-assign": "error",
          "no-compare-neg-zero": "error",
          "no-cond-assign": "error",
          "no-constant-binary-expression": "error",
          "no-constant-condition": "error",
          "no-control-regex": "error",
          "no-debugger": "error",
          "no-delete-var": "error",
          "no-dupe-else-if": "error",
          "no-duplicate-case": "error",
          "no-empty-character-class": "error",
          "no-empty-pattern": "error",
          "no-empty-static-block": "error",
          "no-ex-assign": "error",
          "no-extra-boolean-cast": "error",
          "no-fallthrough": "error",
          "no-global-assign": "error",
          "no-invalid-regexp": "error",
          "no-irregular-whitespace": "error",
          "no-loss-of-precision": "error",
          "no-misleading-character-class": "error",
          "no-nonoctal-decimal-escape": "error",
          "no-regex-spaces": "error",
          "no-self-assign": "error",
          "no-shadow": "warn",
          "no-shadow-restricted-names": "error",
          "no-sparse-arrays": "error",
          "no-unsafe-finally": "error",
          "no-unsafe-optional-chaining": "error",
          "no-unused-labels": "error",
          "no-unused-private-class-members": "error",
          "no-useless-backreference": "error",
          "no-useless-catch": "error",
          "no-useless-escape": "error",
          "no-var": "error",
          "no-with": "error",
          "prefer-const": "error",
          "require-yield": "error",
          "use-isnan": "error",
          "valid-typeof": "error",
          "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
          "import/first": "error",
          "import/newline-after-import": "error",
          "import/no-commonjs": "error",
          "import/no-duplicates": "error",
          "@stylistic/spaced-comment": "error",
          "typescript/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": false,
              "ts-ignore": "allow-with-description",
            },
          ],
          "typescript/consistent-type-imports": [
            "error",
            {
              prefer: "type-imports",
            },
          ],
          "typescript/method-signature-style": ["error", "property"],
          "typescript/no-duplicate-enum-values": "error",
          "typescript/no-extra-non-null-assertion": "error",
          "typescript/no-for-in-array": "error",
          "typescript/no-inferrable-types": [
            "error",
            {
              ignoreParameters: true,
            },
          ],
          "typescript/no-misused-new": "error",
          "typescript/no-namespace": "error",
          "typescript/no-non-null-asserted-optional-chain": "error",
          "typescript/no-unnecessary-type-assertion": "error",
          "typescript/no-unsafe-function-type": "error",
          "typescript/no-wrapper-object-types": "error",
          "typescript/prefer-as-const": "error",
          "typescript/prefer-for-of": "warn",
          "typescript/triple-slash-reference": "error",
        },
      },
    ],
  },
  fmt: {
    endOfLine: "lf",
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    useTabs: false,
    trailingComma: "all",
    printWidth: 100,
    bracketSpacing: true,
    arrowParens: "always",
    insertFinalNewline: true,
    sortImports: true,
    sortTailwindcss: {
      stylesheet: "packages/ui/src/styles/globals.css",
      functions: ["cn", "cva"],
    },
    sortPackageJson: true,
    ignorePatterns: [
      "dist/",
      "node_modules/",
      ".turbo/",
      ".output/",
      ".nitro/",
      ".tanstack/",
      ".vinxi/",
      "coverage/",
      "pnpm-lock.yaml",
      ".pnpm-store/",
      "routeTree.gen.ts",
    ],
  },
  run: {
    tasks: {
      "repo:build": {
        command: "vp run --filter !start-monorepo build",
      },
      "repo:dev": {
        command: "vp run --filter web dev",
        cache: false,
      },
      "repo:lint": {
        command: "vp run --filter !start-monorepo lint",
      },
      "repo:format": {
        command: "vp run --filter !start-monorepo format",
      },
      "repo:typecheck": {
        command: "vp run --filter !start-monorepo typecheck",
      },
    },
  },
});
