/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: b3e4ed1e99aeb393225dc4d6d5e5e45c)
interface __BaseEnv_CloudflareBindings {
	DATABASE: D1Database;
	JOBS_QUEUE: Queue;
	ONESIGNAL_APP_ID: "";
	ONESIGNAL_API_KEY: "";
	DISCORD_WEBHOOK_URL: "";
	CLOUDFLARE_API_TOKEN: "";
	CLOUDFLARE_ZONE_ID: "";
	CLOUDFLARE_CNAME_TARGET: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ONESIGNAL_APP_ID" | "ONESIGNAL_API_KEY" | "DISCORD_WEBHOOK_URL" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ZONE_ID" | "CLOUDFLARE_CNAME_TARGET">> {}
}
