/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: e10daa899d002e48f97930851baecebc)
interface __BaseEnv_CloudflareBindings {
	DATABASE: D1Database;
	JOBS_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
