/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiRemyChatRouteImport } from './routes/api.remy-chat'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoPortfolioRouteImport } from './routes/demo/portfolio'
import { Route as DemoPreviewRouteImport } from './routes/demo/preview'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTypesetRouteImport } from './routes/demo/typeset'
import { Route as ScheduleIndexRouteImport } from './routes/schedule.index'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as SpeakersSlugRouteImport } from './routes/speakers.$slug'
import { Route as TalksIndexRouteImport } from './routes/talks.index'
import { Route as TalksSlugRouteImport } from './routes/talks.$slug'
import { Route as ProtectedSettingsApiKeysRouteImport } from './routes/_protected/settings.api-keys'
import { Route as ProtectedSettingsBillingRouteImport } from './routes/_protected/settings.billing'
import { Route as ProtectedSettingsMembersRouteImport } from './routes/_protected/settings.members'
import { Route as ProtectedSettingsOrganizationRouteImport } from './routes/_protected/settings.organization'
import { Route as ProtectedSettingsSecurityRouteImport } from './routes/_protected/settings.security'
import { Route as ProtectedSettingsTeamsRouteImport } from './routes/_protected/settings.teams'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDebugSentryTestRouteImport } from './routes/api/debug/sentry-test'
import { Route as ApiMediaSplatRouteImport } from './routes/api.media.$'
import { Route as BillingPaystackCallbackRouteImport } from './routes/billing.paystack.callback'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiRemyChatRoute = ApiRemyChatRouteImport.update({
  id: '/api/remy-chat',
  path: '/api/remy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/demo/ai-chat',
  path: '/demo/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/demo/ai-image',
  path: '/demo/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/demo/ai-structured',
  path: '/demo/ai-structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPortfolioRoute = DemoPortfolioRouteImport.update({
  id: '/demo/portfolio',
  path: '/demo/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPreviewRoute = DemoPreviewRouteImport.update({
  id: '/demo/preview',
  path: '/demo/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTypesetRoute = DemoTypesetRouteImport.update({
  id: '/demo/typeset',
  path: '/demo/typeset',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/speakers/$slug',
  path: '/speakers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksSlugRoute = TalksSlugRouteImport.update({
  id: '/talks/$slug',
  path: '/talks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsApiKeysRoute =
  ProtectedSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsBillingRoute =
  ProtectedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsMembersRoute =
  ProtectedSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsOrganizationRoute =
  ProtectedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsSecurityRoute =
  ProtectedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsTeamsRoute = ProtectedSettingsTeamsRouteImport.update({
  id: '/settings/teams',
  path: '/settings/teams',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSentryTestRoute = ApiDebugSentryTestRouteImport.update({
  id: '/api/debug/sentry-test',
  path: '/api/debug/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPaystackCallbackRoute = BillingPaystackCallbackRouteImport.update({
  id: '/billing/paystack/callback',
  path: '/billing/paystack/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/demo/guitars/',
  path: '/demo/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/demo/guitars/$guitarId',
  path: '/demo/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/demo/api/ai/chat',
  path: '/demo/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/demo/api/ai/image',
  path: '/demo/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/demo/api/ai/structured',
  path: '/demo/api/ai/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/demo/api/ai/transcription',
  path: '/demo/api/ai/transcription',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/demo/api/ai/tts',
  path: '/demo/api/ai/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/two-factor': typeof TwoFactorRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/portfolio': typeof DemoPortfolioRoute
  '/demo/preview': typeof DemoPreviewRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/typeset': typeof DemoTypesetRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/members': typeof ProtectedSettingsMembersRoute
  '/settings/organization': typeof ProtectedSettingsOrganizationRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/settings/teams': typeof ProtectedSettingsTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/sentry-test': typeof ApiDebugSentryTestRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/billing/paystack/callback': typeof BillingPaystackCallbackRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/two-factor': typeof TwoFactorRoute
  '/account': typeof ProtectedAccountRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/portfolio': typeof DemoPortfolioRoute
  '/demo/preview': typeof DemoPreviewRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/typeset': typeof DemoTypesetRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/schedule': typeof ScheduleIndexRoute
  '/speakers': typeof SpeakersIndexRoute
  '/talks': typeof TalksIndexRoute
  '/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/members': typeof ProtectedSettingsMembersRoute
  '/settings/organization': typeof ProtectedSettingsOrganizationRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/settings/teams': typeof ProtectedSettingsTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/sentry-test': typeof ApiDebugSentryTestRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/billing/paystack/callback': typeof BillingPaystackCallbackRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/two-factor': typeof TwoFactorRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/portfolio': typeof DemoPortfolioRoute
  '/demo/preview': typeof DemoPreviewRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/typeset': typeof DemoTypesetRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/_protected/settings/api-keys': typeof ProtectedSettingsApiKeysRoute
  '/_protected/settings/billing': typeof ProtectedSettingsBillingRoute
  '/_protected/settings/members': typeof ProtectedSettingsMembersRoute
  '/_protected/settings/organization': typeof ProtectedSettingsOrganizationRoute
  '/_protected/settings/security': typeof ProtectedSettingsSecurityRoute
  '/_protected/settings/teams': typeof ProtectedSettingsTeamsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/debug/sentry-test': typeof ApiDebugSentryTestRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/billing/paystack/callback': typeof BillingPaystackCallbackRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/two-factor'
    | '/account'
    | '/dashboard'
    | '/api/remy-chat'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/portfolio'
    | '/demo/preview'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/typeset'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/security'
    | '/settings/teams'
    | '/api/auth/$'
    | '/api/debug/sentry-test'
    | '/api/media/$'
    | '/billing/paystack/callback'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/sentry/testing'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/two-factor'
    | '/account'
    | '/dashboard'
    | '/api/remy-chat'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/portfolio'
    | '/demo/preview'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/typeset'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/schedule'
    | '/speakers'
    | '/talks'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/security'
    | '/settings/teams'
    | '/api/auth/$'
    | '/api/debug/sentry-test'
    | '/api/media/$'
    | '/billing/paystack/callback'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/sentry/testing'
    | '/demo/guitars'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/accept-invite'
    | '/contact'
    | '/faq'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/two-factor'
    | '/_protected/account'
    | '/_protected/dashboard'
    | '/api/remy-chat'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/better-auth'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/drizzle'
    | '/demo/i18n'
    | '/demo/portfolio'
    | '/demo/preview'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/typeset'
    | '/speakers/$slug'
    | '/talks/$slug'
    | '/schedule/'
    | '/speakers/'
    | '/talks/'
    | '/_protected/settings/api-keys'
    | '/_protected/settings/billing'
    | '/_protected/settings/members'
    | '/_protected/settings/organization'
    | '/_protected/settings/security'
    | '/_protected/settings/teams'
    | '/api/auth/$'
    | '/api/debug/sentry-test'
    | '/api/media/$'
    | '/billing/paystack/callback'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/guitars/$guitarId'
    | '/demo/sentry/testing'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TwoFactorRoute: typeof TwoFactorRoute
  ApiRemyChatRoute: typeof ApiRemyChatRoute
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoPortfolioRoute: typeof DemoPortfolioRoute
  DemoPreviewRoute: typeof DemoPreviewRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoTypesetRoute: typeof DemoTypesetRoute
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  TalksSlugRoute: typeof TalksSlugRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDebugSentryTestRoute: typeof ApiDebugSentryTestRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  BillingPaystackCallbackRoute: typeof BillingPaystackCallbackRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/remy-chat': {
      id: '/api/remy-chat'
      path: '/api/remy-chat'
      fullPath: '/api/remy-chat'
      preLoaderRoute: typeof ApiRemyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/demo/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/demo/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/demo/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/portfolio': {
      id: '/demo/portfolio'
      path: '/demo/portfolio'
      fullPath: '/demo/portfolio'
      preLoaderRoute: typeof DemoPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/preview': {
      id: '/demo/preview'
      path: '/demo/preview'
      fullPath: '/demo/preview'
      preLoaderRoute: typeof DemoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/typeset': {
      id: '/demo/typeset'
      path: '/demo/typeset'
      fullPath: '/demo/typeset'
      preLoaderRoute: typeof DemoTypesetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/speakers/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/$slug': {
      id: '/talks/$slug'
      path: '/talks/$slug'
      fullPath: '/talks/$slug'
      preLoaderRoute: typeof TalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/api-keys': {
      id: '/_protected/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof ProtectedSettingsApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/billing': {
      id: '/_protected/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof ProtectedSettingsBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/members': {
      id: '/_protected/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof ProtectedSettingsMembersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/organization': {
      id: '/_protected/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof ProtectedSettingsOrganizationRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/security': {
      id: '/_protected/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof ProtectedSettingsSecurityRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/teams': {
      id: '/_protected/settings/teams'
      path: '/settings/teams'
      fullPath: '/settings/teams'
      preLoaderRoute: typeof ProtectedSettingsTeamsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/sentry-test': {
      id: '/api/debug/sentry-test'
      path: '/api/debug/sentry-test'
      fullPath: '/api/debug/sentry-test'
      preLoaderRoute: typeof ApiDebugSentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/paystack/callback': {
      id: '/billing/paystack/callback'
      path: '/billing/paystack/callback'
      fullPath: '/billing/paystack/callback'
      preLoaderRoute: typeof BillingPaystackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/demo/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/demo/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/demo/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/demo/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/demo/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/demo/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/demo/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsApiKeysRoute: typeof ProtectedSettingsApiKeysRoute
  ProtectedSettingsBillingRoute: typeof ProtectedSettingsBillingRoute
  ProtectedSettingsMembersRoute: typeof ProtectedSettingsMembersRoute
  ProtectedSettingsOrganizationRoute: typeof ProtectedSettingsOrganizationRoute
  ProtectedSettingsSecurityRoute: typeof ProtectedSettingsSecurityRoute
  ProtectedSettingsTeamsRoute: typeof ProtectedSettingsTeamsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsApiKeysRoute: ProtectedSettingsApiKeysRoute,
  ProtectedSettingsBillingRoute: ProtectedSettingsBillingRoute,
  ProtectedSettingsMembersRoute: ProtectedSettingsMembersRoute,
  ProtectedSettingsOrganizationRoute: ProtectedSettingsOrganizationRoute,
  ProtectedSettingsSecurityRoute: ProtectedSettingsSecurityRoute,
  ProtectedSettingsTeamsRoute: ProtectedSettingsTeamsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TwoFactorRoute: TwoFactorRoute,
  ApiRemyChatRoute: ApiRemyChatRoute,
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoPortfolioRoute: DemoPortfolioRoute,
  DemoPreviewRoute: DemoPreviewRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoTypesetRoute: DemoTypesetRoute,
  SpeakersSlugRoute: SpeakersSlugRoute,
  TalksSlugRoute: TalksSlugRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDebugSentryTestRoute: ApiDebugSentryTestRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  BillingPaystackCallbackRoute: BillingPaystackCallbackRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
