import type { PortfolioData } from "@workspace/ui/components/ui/portfolio-dashboard";

/** Demo portfolio series for the authenticated user dashboard. */
export const demoPortfolioData: PortfolioData = {
  totalBalance: 128_450.32,
  totalPlValue: 12_840.18,
  totalPlPercentage: 11.12,
  riskLevel: "MEDIUM",
  chartData: [
    { date: "Mon", value: 112_400 },
    { date: "Tue", value: 114_200 },
    { date: "Wed", value: 113_100 },
    { date: "Thu", value: 118_900 },
    { date: "Fri", value: 121_300 },
    { date: "Sat", value: 125_800 },
    { date: "Sun", value: 128_450 },
  ],
  assets: [
    {
      id: "btc",
      name: "Bitcoin",
      symbol: "BTC",
      icon: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png",
      price: 97_840,
      holdingsValue: 62_400,
      holdingsAmount: 0.638,
      allocation: 48.6,
      plValue: 8_210,
      plPercentage: 15.1,
      color: "#F7931A",
    },
    {
      id: "eth",
      name: "Ethereum",
      symbol: "ETH",
      icon: "https://assets.coingecko.com/coins/images/279/small/ethereum.png",
      price: 3_412,
      holdingsValue: 41_200,
      holdingsAmount: 12.08,
      allocation: 32.1,
      plValue: 3_420,
      plPercentage: 9.0,
      color: "#627EEA",
    },
    {
      id: "sol",
      name: "Solana",
      symbol: "SOL",
      icon: "https://assets.coingecko.com/coins/images/4128/small/solana.png",
      price: 178,
      holdingsValue: 24_850,
      holdingsAmount: 139.6,
      allocation: 19.3,
      plValue: 1_210,
      plPercentage: 5.1,
      color: "#14F195",
    },
  ],
};
